import dotenv from "dotenv";
import { connectDB } from "./db.js";
import { Company } from "./models/Company.js";

dotenv.config();

const sample = [
  {
    name: "Tata Consultancy Services",
    location: "Mumbai",
    industry: "Information Technology",
    website: "https://www.tcs.com",
    logoUrl: "https://placehold.co/80x80?text=TCS",
    size: 600000,
    foundedYear: 1968,
    revenue: "₹2.25T",
    description:
      "TCS is a leading global IT services, consulting, and business solutions organization.",
    contact: { email: "contact@tcs.com", phone: "+91-22-6778-9999" },
    address: {
      street: "Nirmal Building, Nariman Point",
      city: "Mumbai",
      state: "MH",
      postalCode: "400021",
      country: "India",
    },
  },
  {
    name: "Reliance Industries",
    location: "Mumbai",
    industry: "Conglomerate",
    website: "https://www.ril.com",
    logoUrl: "https://placehold.co/80x80?text=RIL",
    size: 389000,
    foundedYear: 1966,
    revenue: "₹9.7T",
    description:
      "Reliance operates across energy, petrochemicals, retail, telecom, and digital services.",
    contact: { email: "info@ril.com", phone: "+91-22-3555-5000" },
    address: {
      street: "Maker Chambers IV, Nariman Point",
      city: "Mumbai",
      state: "MH",
      postalCode: "400021",
      country: "India",
    },
  },
  {
    name: "Infosys",
    location: "Bengaluru",
    industry: "Information Technology",
    website: "https://www.infosys.com",
    logoUrl: "https://placehold.co/80x80?text=INFY",
    size: 345000,
    foundedYear: 1981,
    revenue: "₹1.55T",
    description:
      "Infosys is a global leader in next-generation digital services and consulting.",
    contact: { email: "contact@infosys.com", phone: "+91-80-2852-0261" },
    address: {
      street: "Electronics City, Hosur Road",
      city: "Bengaluru",
      state: "KA",
      postalCode: "560100",
      country: "India",
    },
  },
  {
    name: "Wipro",
    location: "Bengaluru",
    industry: "Information Technology",
    website: "https://www.wipro.com",
    logoUrl: "https://placehold.co/80x80?text=Wipro",
    size: 240000,
    foundedYear: 1945,
    revenue: "₹0.89T",
    description:
      "Wipro is a technology services and consulting company focused on building innovative solutions.",
    contact: { email: "info@wipro.com", phone: "+91-80-2844-0011" },
    address: {
      street: "Doddakannelli, Sarjapur Road",
      city: "Bengaluru",
      state: "KA",
      postalCode: "560035",
      country: "India",
    },
  },
  {
    name: "HDFC Bank",
    location: "Mumbai",
    industry: "Banking",
    website: "https://www.hdfcbank.com",
    logoUrl: "https://placehold.co/80x80?text=HDFC",
    size: 180000,
    foundedYear: 1994,
    revenue: "₹2.0T",
    description:
      "HDFC Bank is one of India’s leading private sector banks providing a wide range of banking services.",
    contact: { email: "support@hdfcbank.com", phone: "1800-1600" },
    address: {
      street: "Senapati Bapat Marg, Lower Parel",
      city: "Mumbai",
      state: "MH",
      postalCode: "400013",
      country: "India",
    },
  },
  {
    name: "ICICI Bank",
    location: "Mumbai",
    industry: "Banking",
    website: "https://www.icicibank.com",
    logoUrl: "https://placehold.co/80x80?text=ICICI",
    size: 130000,
    foundedYear: 1994,
    revenue: "₹1.3T",
    description:
      "ICICI Bank is a leading private bank in India with a robust digital footprint.",
    contact: { email: "care@icicibank.com", phone: "1860-120-7777" },
    address: {
      street: "ICICI Bank Towers, BKC",
      city: "Mumbai",
      state: "MH",
      postalCode: "400051",
      country: "India",
    },
  },
  {
    name: "HCLTech",
    location: "Noida",
    industry: "Information Technology",
    website: "https://www.hcltech.com",
    logoUrl: "https://placehold.co/80x80?text=HCL",
    size: 224000,
    foundedYear: 1976,
    revenue: "₹1.1T",
    description:
      "HCLTech delivers industry-leading capabilities centered around digital, engineering, and cloud.",
    contact: { email: "contact@hcl.com", phone: "+91-120-406-3000" },
    address: {
      street: "A-10/11, Sector 3",
      city: "Noida",
      state: "UP",
      postalCode: "201301",
      country: "India",
    },
  },
  {
    name: "Adani Group",
    location: "Ahmedabad",
    industry: "Conglomerate",
    website: "https://www.adani.com",
    logoUrl: "https://placehold.co/80x80?text=Adani",
    size: 230000,
    foundedYear: 1988,
    revenue: "₹1.6T",
    description:
      "Adani Group operates across energy, logistics, agribusiness, and infrastructure.",
    contact: { email: "info@adani.com", phone: "+91-79-2555-5555" },
    address: {
      street: "Adani House, Navrangpura",
      city: "Ahmedabad",
      state: "GJ",
      postalCode: "380009",
      country: "India",
    },
  },
  {
    name: "Tata Steel",
    location: "Mumbai",
    industry: "Steel",
    website: "https://www.tatasteel.com",
    logoUrl: "https://placehold.co/80x80?text=TSteel",
    size: 77000,
    foundedYear: 1907,
    revenue: "₹2.4T",
    description:
      "Tata Steel is one of the world’s most geographically diversified steel producers.",
    contact: { email: "corporate@tatasteel.com", phone: "+91-33-66-111-111" },
    address: {
      street: "Tata Centre, 43 Chowringhee",
      city: "Kolkata",
      state: "WB",
      postalCode: "700071",
      country: "India",
    },
  },
  {
    name: "Zomato",
    location: "Gurugram",
    industry: "Foodtech",
    website: "https://www.zomato.com",
    logoUrl: "https://placehold.co/80x80?text=Zomato",
    size: 8500,
    foundedYear: 2008,
    revenue: "₹100B",
    description:
      "Zomato is a technology platform connecting customers, restaurant partners, and delivery partners.",
    contact: { email: "help@zomato.com", phone: "+91-11-3080-3450" },
    address: {
      street: "DLF Phase 5",
      city: "Gurugram",
      state: "HR",
      postalCode: "122002",
      country: "India",
    },
  },
  {
    name: "Tech Mahindra",
    location: "Pune",
    industry: "Information Technology",
    website: "https://www.techmahindra.com",
    logoUrl: "https://placehold.co/80x80?text=TechM",
    size: 150000,
    foundedYear: 1986,
    revenue: "₹0.53T",
    description:
      "Tech Mahindra provides IT services and digital transformation for global enterprises.",
    contact: { email: "info@techmahindra.com", phone: "+91-20-6601-8100" },
    address: {
      street: "Rajiv Gandhi Infotech Park",
      city: "Pune",
      state: "MH",
      postalCode: "411057",
      country: "India",
    },
  },
  {
    name: "LTIMindtree",
    location: "Bengaluru",
    industry: "Information Technology",
    website: "https://www.ltimindtree.com",
    logoUrl: "https://placehold.co/80x80?text=LTIM",
    size: 82000,
    foundedYear: 1996,
    revenue: "₹0.36T",
    description:
      "LTIMindtree is a global technology consulting and digital solutions company.",
    contact: { email: "info@ltimindtree.com", phone: "+91-80-6706-4000" },
    address: {
      street: "Global Village Tech Park",
      city: "Bengaluru",
      state: "KA",
      postalCode: "560059",
      country: "India",
    },
  },
  {
    name: "Mphasis",
    location: "Bengaluru",
    industry: "Information Technology",
    website: "https://www.mphasis.com",
    logoUrl: "https://placehold.co/80x80?text=Mphasis",
    size: 39000,
    foundedYear: 1998,
    revenue: "₹0.13T",
    description:
      "Mphasis applies next-gen technology to help enterprises transform businesses globally.",
    contact: { email: "info@mphasis.com", phone: "+91-80-4004-4444" },
    address: {
      street: "Bagmane World Technology Center",
      city: "Bengaluru",
      state: "KA",
      postalCode: "560093",
      country: "India",
    },
  },
  {
    name: "Persistent Systems",
    location: "Pune",
    industry: "Information Technology",
    website: "https://www.persistent.com",
    logoUrl: "https://placehold.co/80x80?text=Persistent",
    size: 23000,
    foundedYear: 1990,
    revenue: "₹0.14T",
    description:
      "Persistent Systems builds software products and digital engineering solutions.",
    contact: { email: "info@persistent.com", phone: "+91-20-6703-0000" },
    address: {
      street: "S. No. 36/3B/1, Pune IT Park",
      city: "Pune",
      state: "MH",
      postalCode: "411016",
      country: "India",
    },
  },
  {
    name: "Coforge",
    location: "Noida",
    industry: "Information Technology",
    website: "https://www.coforge.com",
    logoUrl: "https://placehold.co/80x80?text=Coforge",
    size: 24000,
    foundedYear: 1992,
    revenue: "₹0.09T",
    description: "Coforge is a global digital services and solutions provider.",
    contact: { email: "contact@coforge.com", phone: "+91-120-401-2700" },
    address: {
      street: "Plot No.45, Sector 32",
      city: "Noida",
      state: "UP",
      postalCode: "201301",
      country: "India",
    },
  },
  {
    name: "Hexaware",
    location: "Navi Mumbai",
    industry: "Information Technology",
    website: "https://hexaware.com",
    logoUrl: "https://placehold.co/80x80?text=Hexaware",
    size: 28000,
    foundedYear: 1990,
    revenue: "₹0.08T",
    description:
      "Hexaware provides IT, BPO, and consulting services focused on automation and cloud.",
    contact: { email: "info@hexaware.com", phone: "+91-22-6795-3000" },
    address: {
      street: "MIDC, TTC Industrial Area",
      city: "Navi Mumbai",
      state: "MH",
      postalCode: "400705",
      country: "India",
    },
  },
  {
    name: "Oracle Financial Services Software",
    location: "Mumbai",
    industry: "Software",
    website: "https://www.oracle.com/industries/financial-services/ofss/",
    logoUrl: "https://placehold.co/80x80?text=OFSS",
    size: 9000,
    foundedYear: 1991,
    revenue: "₹0.05T",
    description: "OFSS provides IT solutions to the global banking industry.",
    contact: { email: "contact@oracle.com", phone: "+91-22-6718-3000" },
    address: {
      street: "Oracle Park, Powai",
      city: "Mumbai",
      state: "MH",
      postalCode: "400076",
      country: "India",
    },
  },
  {
    name: "Zoho",
    location: "Chennai",
    industry: "Software",
    website: "https://www.zoho.com",
    logoUrl: "https://placehold.co/80x80?text=Zoho",
    size: 15000,
    foundedYear: 1996,
    revenue: "Private",
    description:
      "Zoho builds a suite of online productivity, collaboration, and business applications.",
    contact: { email: "sales@zohocorp.com", phone: "+91-44-7181-7070" },
    address: {
      street: "Estancia IT Park",
      city: "Chennai",
      state: "TN",
      postalCode: "603202",
      country: "India",
    },
  },
  {
    name: "Freshworks",
    location: "Chennai",
    industry: "Software",
    website: "https://www.freshworks.com",
    logoUrl: "https://placehold.co/80x80?text=Fresh",
    size: 5500,
    foundedYear: 2010,
    revenue: "$0.6B",
    description: "Freshworks builds cloud-based customer engagement software.",
    contact: { email: "sales@freshworks.com", phone: "+91-44-4202-2805" },
    address: {
      street: "SP Infocity",
      city: "Chennai",
      state: "TN",
      postalCode: "600042",
      country: "India",
    },
  },
  {
    name: "ThoughtWorks India",
    location: "Bengaluru",
    industry: "Software",
    website: "https://www.thoughtworks.com",
    logoUrl: "https://placehold.co/80x80?text=TW",
    size: 2500,
    foundedYear: 1993,
    revenue: "Private",
    description:
      "ThoughtWorks is a global technology consultancy that integrates strategy, design and software engineering.",
    contact: { email: "info@thoughtworks.com", phone: "+91-80-6658-6000" },
    address: {
      street: "Millenia Tower",
      city: "Bengaluru",
      state: "KA",
      postalCode: "560071",
      country: "India",
    },
  },
  {
    name: "SAP Labs India",
    location: "Bengaluru",
    industry: "Software",
    website: "https://www.sap.com/india",
    logoUrl: "https://placehold.co/80x80?text=SAP",
    size: 15000,
    foundedYear: 1998,
    revenue: "€31B (SAP SE)",
    description: "SAP Labs India is SAP’s largest R&D center outside Germany.",
    contact: { email: "info.india@sap.com", phone: "+91-80-6665-6000" },
    address: {
      street: "RMZ Ecoworld",
      city: "Bengaluru",
      state: "KA",
      postalCode: "560103",
      country: "India",
    },
  },
  {
    name: "Microsoft",
    location: "Redmond",
    industry: "Software",
    website: "https://www.microsoft.com",
    logoUrl: "https://placehold.co/80x80?text=MSFT",
    size: 230000,
    foundedYear: 1975,
    revenue: "$211B",
    description:
      "Microsoft develops software, services, devices, and solutions worldwide.",
    contact: { email: "support@microsoft.com", phone: "+1-425-882-8080" },
    address: {
      street: "One Microsoft Way",
      city: "Redmond",
      state: "WA",
      postalCode: "98052",
      country: "USA",
    },
  },
  {
    name: "Google",
    location: "Mountain View",
    industry: "Software",
    website: "https://www.google.com",
    logoUrl: "https://placehold.co/80x80?text=Google",
    size: 180000,
    foundedYear: 1998,
    revenue: "$307B",
    description:
      "Google specializes in internet-related services and products, including search and cloud.",
    contact: { email: "press@google.com", phone: "+1-650-253-0000" },
    address: {
      street: "1600 Amphitheatre Parkway",
      city: "Mountain View",
      state: "CA",
      postalCode: "94043",
      country: "USA",
    },
  },
  {
    name: "Amazon",
    location: "Seattle",
    industry: "Software",
    website: "https://www.amazon.com",
    logoUrl: "https://placehold.co/80x80?text=Amazon",
    size: 1500000,
    foundedYear: 1994,
    revenue: "$575B",
    description:
      "Amazon is a technology company focusing on e-commerce, cloud computing (AWS), and AI.",
    contact: { email: "pr@amazon.com", phone: "+1-206-266-1000" },
    address: {
      street: "410 Terry Ave N",
      city: "Seattle",
      state: "WA",
      postalCode: "98109",
      country: "USA",
    },
  },
  {
    name: "Apple",
    location: "Cupertino",
    industry: "Software",
    website: "https://www.apple.com",
    logoUrl: "https://placehold.co/80x80?text=Apple",
    size: 161000,
    foundedYear: 1976,
    revenue: "$383B",
    description:
      "Apple designs, manufactures, and markets smartphones, PCs, tablets, wearables, and services.",
    contact: { email: "media.help@apple.com", phone: "+1-408-996-1010" },
    address: {
      street: "One Apple Park Way",
      city: "Cupertino",
      state: "CA",
      postalCode: "95014",
      country: "USA",
    },
  },
  {
    name: "Meta",
    location: "Menlo Park",
    industry: "Software",
    website: "https://about.meta.com",
    logoUrl: "https://placehold.co/80x80?text=Meta",
    size: 86000,
    foundedYear: 2004,
    revenue: "$135B",
    description:
      "Meta builds technologies that help people connect, find communities, and grow businesses.",
    contact: { email: "press@fb.com", phone: "+1-650-543-4800" },
    address: {
      street: "1 Hacker Way",
      city: "Menlo Park",
      state: "CA",
      postalCode: "94025",
      country: "USA",
    },
  },
  {
    name: "Netflix",
    location: "Los Gatos",
    industry: "Software",
    website: "https://www.netflix.com",
    logoUrl: "https://placehold.co/80x80?text=Netflix",
    size: 13000,
    foundedYear: 1997,
    revenue: "$34B",
    description:
      "Netflix is a streaming entertainment service producing and distributing content globally.",
    contact: { email: "pr@netflix.com", phone: "+1-408-540-3700" },
    address: {
      street: "100 Winchester Circle",
      city: "Los Gatos",
      state: "CA",
      postalCode: "95032",
      country: "USA",
    },
  },
  {
    name: "Adobe",
    location: "San Jose",
    industry: "Software",
    website: "https://www.adobe.com",
    logoUrl: "https://placehold.co/80x80?text=Adobe",
    size: 29000,
    foundedYear: 1982,
    revenue: "$21B",
    description:
      "Adobe provides digital media and marketing solutions like Photoshop, Acrobat, and Experience Cloud.",
    contact: { email: "media@adobe.com", phone: "+1-408-536-6000" },
    address: {
      street: "345 Park Avenue",
      city: "San Jose",
      state: "CA",
      postalCode: "95110",
      country: "USA",
    },
  },
  {
    name: "Salesforce",
    location: "San Francisco",
    industry: "Software",
    website: "https://www.salesforce.com",
    logoUrl: "https://placehold.co/80x80?text=SFDC",
    size: 70000,
    foundedYear: 1999,
    revenue: "$35B",
    description:
      "Salesforce is the leading customer relationship management (CRM) platform.",
    contact: { email: "pr@salesforce.com", phone: "+1-415-901-7000" },
    address: {
      street: "Salesforce Tower, 415 Mission St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94105",
      country: "USA",
    },
  },
  {
    name: "SAP",
    location: "Walldorf",
    industry: "Software",
    website: "https://www.sap.com",
    logoUrl: "https://placehold.co/80x80?text=SAP",
    size: 105000,
    foundedYear: 1972,
    revenue: "€31B",
    description: "SAP is a market leader in enterprise application software.",
    contact: { email: "press@sap.com", phone: "+49-6227-747474" },
    address: {
      street: "Dietmar-Hopp-Allee 16",
      city: "Walldorf",
      state: "BW",
      postalCode: "69190",
      country: "Germany",
    },
  },
  {
    name: "Oracle",
    location: "Austin",
    industry: "Software",
    website: "https://www.oracle.com",
    logoUrl: "https://placehold.co/80x80?text=Oracle",
    size: 164000,
    foundedYear: 1977,
    revenue: "$52B",
    description:
      "Oracle provides enterprise software, database technology, and cloud services.",
    contact: { email: "media_ww@oracle.com", phone: "+1-737-867-1000" },
    address: {
      street: "2300 Oracle Way",
      city: "Austin",
      state: "TX",
      postalCode: "78741",
      country: "USA",
    },
  },
  {
    name: "IBM",
    location: "Armonk",
    industry: "Software",
    website: "https://www.ibm.com",
    logoUrl: "https://placehold.co/80x80?text=IBM",
    size: 288000,
    foundedYear: 1911,
    revenue: "$62B",
    description:
      "IBM is a global technology innovator in hybrid cloud and AI, with consulting expertise.",
    contact: { email: "press@us.ibm.com", phone: "+1-914-499-1900" },
    address: {
      street: "1 New Orchard Road",
      city: "Armonk",
      state: "NY",
      postalCode: "10504",
      country: "USA",
    },
  },
  {
    name: "Cisco",
    location: "San Jose",
    industry: "Software",
    website: "https://www.cisco.com",
    logoUrl: "https://placehold.co/80x80?text=Cisco",
    size: 84000,
    foundedYear: 1984,
    revenue: "$57B",
    description:
      "Cisco designs and sells networking, security, collaboration, and cloud solutions.",
    contact: { email: "press@cisco.com", phone: "+1-408-526-4000" },
    address: {
      street: "170 West Tasman Dr",
      city: "San Jose",
      state: "CA",
      postalCode: "95134",
      country: "USA",
    },
  },
  {
    name: "VMware",
    location: "Palo Alto",
    industry: "Software",
    website: "https://www.vmware.com",
    logoUrl: "https://placehold.co/80x80?text=VMW",
    size: 38000,
    foundedYear: 1998,
    revenue: "$13B",
    description:
      "VMware provides multi-cloud services for apps, enabling digital innovation.",
    contact: { email: "press@vmware.com", phone: "+1-877-486-9273" },
    address: {
      street: "3401 Hillview Ave",
      city: "Palo Alto",
      state: "CA",
      postalCode: "94304",
      country: "USA",
    },
  },
  {
    name: "Atlassian",
    location: "Sydney",
    industry: "Software",
    website: "https://www.atlassian.com",
    logoUrl: "https://placehold.co/80x80?text=Atlassian",
    size: 11000,
    foundedYear: 2002,
    revenue: "$4B",
    description:
      "Atlassian builds tools like Jira, Confluence, and Bitbucket for teams.",
    contact: { email: "press@atlassian.com", phone: "+61-2-9262-1443" },
    address: {
      street: "341 George St",
      city: "Sydney",
      state: "NSW",
      postalCode: "2000",
      country: "Australia",
    },
  },
  {
    name: "Snowflake",
    location: "Bozeman",
    industry: "Software",
    website: "https://www.snowflake.com",
    logoUrl: "https://placehold.co/80x80?text=Snowflake",
    size: 6900,
    foundedYear: 2012,
    revenue: "$3B",
    description:
      "Snowflake provides a cloud data platform with data warehousing and analytics.",
    contact: { email: "media@snowflake.com", phone: "+1-844-766-9355" },
    address: {
      street: "106 E Babcock St",
      city: "Bozeman",
      state: "MT",
      postalCode: "59715",
      country: "USA",
    },
  },
  {
    name: "Stripe",
    location: "San Francisco",
    industry: "Software",
    website: "https://stripe.com",
    logoUrl: "https://placehold.co/80x80?text=Stripe",
    size: 7000,
    foundedYear: 2010,
    revenue: "Private",
    description: "Stripe builds financial infrastructure for the internet.",
    contact: { email: "press@stripe.com", phone: "+1-888-963-8955" },
    address: {
      street: "354 Oyster Point Blvd",
      city: "South San Francisco",
      state: "CA",
      postalCode: "94080",
      country: "USA",
    },
  },
  {
    name: "Uber",
    location: "San Francisco",
    industry: "Software",
    website: "https://www.uber.com",
    logoUrl: "https://placehold.co/80x80?text=Uber",
    size: 30000,
    foundedYear: 2009,
    revenue: "$37B",
    description:
      "Uber develops and operates technology applications supporting ridesharing and delivery.",
    contact: { email: "press@uber.com", phone: "+1-415-612-8582" },
    address: {
      street: "1725 3rd St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94158",
      country: "USA",
    },
  },
  {
    name: "Airbnb",
    location: "San Francisco",
    industry: "Software",
    website: "https://www.airbnb.com",
    logoUrl: "https://placehold.co/80x80?text=Airbnb",
    size: 6100,
    foundedYear: 2008,
    revenue: "$10B",
    description:
      "Airbnb operates an online marketplace for lodging and experiences.",
    contact: { email: "press@airbnb.com", phone: "+1-855-424-7262" },
    address: {
      street: "888 Brannan St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94103",
      country: "USA",
    },
  },
  {
    name: "Spotify",
    location: "Stockholm",
    industry: "Software",
    website: "https://www.spotify.com",
    logoUrl: "https://placehold.co/80x80?text=Spotify",
    size: 9800,
    foundedYear: 2006,
    revenue: "$13B",
    description: "Spotify provides audio streaming services globally.",
    contact: { email: "press@spotify.com", phone: "+46-8-5780-3000" },
    address: {
      street: "Regeringsgatan 19",
      city: "Stockholm",
      state: "",
      postalCode: "111 53",
      country: "Sweden",
    },
  },
  {
    name: "Shopify",
    location: "Ottawa",
    industry: "Software",
    website: "https://www.shopify.com",
    logoUrl: "https://placehold.co/80x80?text=Shopify",
    size: 11000,
    foundedYear: 2006,
    revenue: "$7B",
    description: "Shopify provides commerce platform solutions for merchants.",
    contact: { email: "press@shopify.com", phone: "+1-613-241-2828" },
    address: {
      street: "151 O'Connor St",
      city: "Ottawa",
      state: "ON",
      postalCode: "K2P 2L8",
      country: "Canada",
    },
  },
  {
    name: "Palantir",
    location: "Denver",
    industry: "Software",
    website: "https://www.palantir.com",
    logoUrl: "https://placehold.co/80x80?text=Palantir",
    size: 3800,
    foundedYear: 2003,
    revenue: "$2.2B",
    description:
      "Palantir builds software that empowers organizations to integrate, analyze, and act on data.",
    contact: { email: "press@palantir.com", phone: "+1-720-358-3679" },
    address: {
      street: "1555 Blake St",
      city: "Denver",
      state: "CO",
      postalCode: "80202",
      country: "USA",
    },
  },
  {
    name: "ServiceNow",
    location: "Santa Clara",
    industry: "Software",
    website: "https://www.servicenow.com",
    logoUrl: "https://placehold.co/80x80?text=SNOW",
    size: 22000,
    foundedYear: 2004,
    revenue: "$8.6B",
    description:
      "ServiceNow makes the world work better for everyone with cloud‑based platforms.",
    contact: { email: "media@servicenow.com", phone: "+1-408-501-8550" },
    address: {
      street: "2225 Lawson Ln",
      city: "Santa Clara",
      state: "CA",
      postalCode: "95054",
      country: "USA",
    },
  },
  {
    name: "Cloudflare",
    location: "San Francisco",
    industry: "Software",
    website: "https://www.cloudflare.com",
    logoUrl: "https://placehold.co/80x80?text=Cloudflare",
    size: 3500,
    foundedYear: 2009,
    revenue: "$1.3B",
    description:
      "Cloudflare secures and accelerates internet applications globally.",
    contact: { email: "press@cloudflare.com", phone: "+1-888-993-5273" },
    address: {
      street: "101 Townsend St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94107",
      country: "USA",
    },
  },
  {
    name: "Datadog",
    location: "New York",
    industry: "Software",
    website: "https://www.datadoghq.com",
    logoUrl: "https://placehold.co/80x80?text=Datadog",
    size: 6000,
    foundedYear: 2010,
    revenue: "$2.7B",
    description:
      "Datadog offers monitoring and security for cloud applications.",
    contact: { email: "press@datadoghq.com", phone: "+1-866-329-4466" },
    address: {
      street: "620 8th Ave",
      city: "New York",
      state: "NY",
      postalCode: "10018",
      country: "USA",
    },
  },
  {
    name: "Twilio",
    location: "San Francisco",
    industry: "Software",
    website: "https://www.twilio.com",
    logoUrl: "https://placehold.co/80x80?text=Twilio",
    size: 7800,
    foundedYear: 2008,
    revenue: "$4.1B",
    description:
      "Twilio provides programmable communication tools for making and receiving phone calls, texts, and more.",
    contact: { email: "press@twilio.com", phone: "+1-415-390-2337" },
    address: {
      street: "101 Spear St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94105",
      country: "USA",
    },
  },
  {
    name: "MongoDB, Inc.",
    location: "New York",
    industry: "Software",
    website: "https://www.mongodb.com",
    logoUrl: "https://placehold.co/80x80?text=MongoDB",
    size: 5400,
    foundedYear: 2007,
    revenue: "$1.6B",
    description:
      "MongoDB is a developer data platform company behind the MongoDB database.",
    contact: { email: "pr@mongodb.com", phone: "+1-646-727-4092" },
    address: {
      street: "1633 Broadway",
      city: "New York",
      state: "NY",
      postalCode: "10019",
      country: "USA",
    },
  },
  {
    name: "Elastic",
    location: "Amsterdam",
    industry: "Software",
    website: "https://www.elastic.co",
    logoUrl: "https://placehold.co/80x80?text=Elastic",
    size: 3000,
    foundedYear: 2012,
    revenue: "$1.3B",
    description:
      "Elastic builds self-managed and SaaS offerings for search, logging, security, and analytics.",
    contact: { email: "press@elastic.co", phone: "+31-20-794-1093" },
    address: {
      street: "Keizersgracht 281",
      city: "Amsterdam",
      state: "",
      postalCode: "1016 ED",
      country: "Netherlands",
    },
  },
  {
    name: "HashiCorp",
    location: "San Francisco",
    industry: "Software",
    website: "https://www.hashicorp.com",
    logoUrl: "https://placehold.co/80x80?text=HashiCorp",
    size: 2000,
    foundedYear: 2012,
    revenue: "$0.6B",
    description:
      "HashiCorp provides infrastructure automation for multi-cloud environments.",
    contact: { email: "press@hashicorp.com", phone: "+1-415-301-3250" },
    address: {
      street: "101 2nd St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94105",
      country: "USA",
    },
  },
  {
    name: "GitHub",
    location: "San Francisco",
    industry: "Software",
    website: "https://github.com",
    logoUrl: "https://placehold.co/80x80?text=GitHub",
    size: 3000,
    foundedYear: 2008,
    revenue: "Microsoft",
    description:
      "GitHub is a developer platform for code hosting, collaboration, and CI/CD.",
    contact: { email: "press@github.com", phone: "+1-877-448-4820" },
    address: {
      street: "88 Colin P Kelly Jr St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94107",
      country: "USA",
    },
  },
  {
    name: "GitLab",
    location: "San Francisco",
    industry: "Software",
    website: "https://about.gitlab.com",
    logoUrl: "https://placehold.co/80x80?text=GitLab",
    size: 2000,
    foundedYear: 2011,
    revenue: "$0.6B",
    description:
      "GitLab is a DevSecOps platform delivered as a single application.",
    contact: { email: "pr@gitlab.com", phone: "+1-415-612-3950" },
    address: {
      street: "268 Bush St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94104",
      country: "USA",
    },
  },
];

async function run() {
  try {
    await connectDB(process.env.MONGODB_URI);
    await Company.deleteMany({});
    await Company.insertMany(sample);
    console.log("Seeded companies:", sample.length);
    process.exit(0);
  } catch (e) {
    console.error(e);
    process.exit(1);
  }
}

run();
